# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.button1 = QtWidgets.QPushButton(self.centralWidget)
        self.button1.setGeometry(QtCore.QRect(320, 70, 141, 71))
        self.button1.setMinimumSize(QtCore.QSize(141, 71))
        self.button1.setMaximumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralWidget)
        self.button2.setGeometry(QtCore.QRect(320, 150, 141, 71))
        self.button2.setMinimumSize(QtCore.QSize(141, 71))
        self.button2.setMaximumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button2.setObjectName("button2")
        self.label_status_lbl = QtWidgets.QLabel(self.centralWidget)
        self.label_status_lbl.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.label_status_lbl.setMinimumSize(QtCore.QSize(111, 31))
        self.label_status_lbl.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_status_lbl.setFont(font)
        self.label_status_lbl.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_status_lbl.setObjectName("label_status_lbl")
        self.status_label = QtWidgets.QLabel(self.centralWidget)
        self.status_label.setGeometry(QtCore.QRect(120, 0, 131, 31))
        self.status_label.setMinimumSize(QtCore.QSize(131, 31))
        self.status_label.setMaximumSize(QtCore.QSize(131, 31))
        self.status_label.setStyleSheet("color: rgb(255, 255, 255)")
        self.status_label.setObjectName("status_label")
        self.button3 = QtWidgets.QPushButton(self.centralWidget)
        self.button3.setGeometry(QtCore.QRect(320, 230, 141, 71))
        self.button3.setMinimumSize(QtCore.QSize(141, 71))
        self.button3.setMaximumSize(QtCore.QSize(141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button3.setFont(font)
        self.button3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.button3.setObjectName("button3")
        self.noOneButton = QtWidgets.QPushButton(self.centralWidget)
        self.noOneButton.setGeometry(QtCore.QRect(10, 30, 71, 61))
        self.noOneButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noOneButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noOneButton.setFont(font)
        self.noOneButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noOneButton.setObjectName("noOneButton")
        self.noTwoButton = QtWidgets.QPushButton(self.centralWidget)
        self.noTwoButton.setGeometry(QtCore.QRect(90, 30, 71, 61))
        self.noTwoButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noTwoButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noTwoButton.setFont(font)
        self.noTwoButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noTwoButton.setObjectName("noTwoButton")
        self.noThreeButton = QtWidgets.QPushButton(self.centralWidget)
        self.noThreeButton.setGeometry(QtCore.QRect(170, 30, 71, 61))
        self.noThreeButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noThreeButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noThreeButton.setFont(font)
        self.noThreeButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noThreeButton.setObjectName("noThreeButton")
        self.noSixButton = QtWidgets.QPushButton(self.centralWidget)
        self.noSixButton.setGeometry(QtCore.QRect(170, 100, 71, 61))
        self.noSixButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noSixButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noSixButton.setFont(font)
        self.noSixButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noSixButton.setObjectName("noSixButton")
        self.noFiveButton = QtWidgets.QPushButton(self.centralWidget)
        self.noFiveButton.setGeometry(QtCore.QRect(90, 100, 71, 61))
        self.noFiveButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noFiveButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noFiveButton.setFont(font)
        self.noFiveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noFiveButton.setObjectName("noFiveButton")
        self.noFourButton = QtWidgets.QPushButton(self.centralWidget)
        self.noFourButton.setGeometry(QtCore.QRect(10, 100, 71, 61))
        self.noFourButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noFourButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noFourButton.setFont(font)
        self.noFourButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noFourButton.setObjectName("noFourButton")
        self.noNineButton = QtWidgets.QPushButton(self.centralWidget)
        self.noNineButton.setGeometry(QtCore.QRect(170, 170, 71, 61))
        self.noNineButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noNineButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noNineButton.setFont(font)
        self.noNineButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noNineButton.setObjectName("noNineButton")
        self.noEightButton = QtWidgets.QPushButton(self.centralWidget)
        self.noEightButton.setGeometry(QtCore.QRect(90, 170, 71, 61))
        self.noEightButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noEightButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noEightButton.setFont(font)
        self.noEightButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noEightButton.setObjectName("noEightButton")
        self.noSevenButton = QtWidgets.QPushButton(self.centralWidget)
        self.noSevenButton.setGeometry(QtCore.QRect(10, 170, 71, 61))
        self.noSevenButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noSevenButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noSevenButton.setFont(font)
        self.noSevenButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noSevenButton.setObjectName("noSevenButton")
        self.noPoundButton = QtWidgets.QPushButton(self.centralWidget)
        self.noPoundButton.setGeometry(QtCore.QRect(170, 240, 71, 61))
        self.noPoundButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noPoundButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.noPoundButton.setFont(font)
        self.noPoundButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noPoundButton.setObjectName("noPoundButton")
        self.noZeroButton = QtWidgets.QPushButton(self.centralWidget)
        self.noZeroButton.setGeometry(QtCore.QRect(90, 240, 71, 61))
        self.noZeroButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noZeroButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noZeroButton.setFont(font)
        self.noZeroButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noZeroButton.setObjectName("noZeroButton")
        self.noAstButton = QtWidgets.QPushButton(self.centralWidget)
        self.noAstButton.setGeometry(QtCore.QRect(10, 240, 71, 61))
        self.noAstButton.setMinimumSize(QtCore.QSize(71, 61))
        self.noAstButton.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.noAstButton.setFont(font)
        self.noAstButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noAstButton.setObjectName("noAstButton")
        self.key_label = QtWidgets.QLabel(self.centralWidget)
        self.key_label.setGeometry(QtCore.QRect(320, 20, 131, 31))
        self.key_label.setMinimumSize(QtCore.QSize(131, 31))
        self.key_label.setMaximumSize(QtCore.QSize(131, 31))
        self.key_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_label.setObjectName("key_label")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Alarm"))
        self.button1.setText(_translate("MainWindow", "Armed Away"))
        self.button2.setText(_translate("MainWindow", "Armed Home"))
        self.label_status_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600;\">Alarm Status:   </span></p></body></html>"))
        self.status_label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.button3.setText(_translate("MainWindow", "Disarm"))
        self.noOneButton.setText(_translate("MainWindow", "1"))
        self.noTwoButton.setText(_translate("MainWindow", "2"))
        self.noThreeButton.setText(_translate("MainWindow", "3"))
        self.noSixButton.setText(_translate("MainWindow", "6"))
        self.noFiveButton.setText(_translate("MainWindow", "5"))
        self.noFourButton.setText(_translate("MainWindow", "4"))
        self.noNineButton.setText(_translate("MainWindow", "9"))
        self.noEightButton.setText(_translate("MainWindow", "8"))
        self.noSevenButton.setText(_translate("MainWindow", "7"))
        self.noPoundButton.setText(_translate("MainWindow", "#"))
        self.noZeroButton.setText(_translate("MainWindow", "0"))
        self.noAstButton.setText(_translate("MainWindow", "*"))
        self.key_label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))

